=== NagendraThakur/Music-Store-XML/catalog_19031172.xsd
<!--
  Developer: Nagendra Thakur Sharma
  Date: 5/2/2021
-->
<!-- Salami Slice  -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="singer_first_name" type="xs:string"/>
  <xs:element name="singer_last_name" type="xs:string"/>
  <xs:element name="director_first_name" type="xs:string"/>
  <xs:element name="director_last_name" type="xs:string"/>
  <xs:element name="producer_first_name" type="xs:string"/>
  <xs:element name="producer_last_name" type="xs:string"/>
  <xs:element name="writer_first_name" type="xs:string"/>
  <xs:element name="writer_last_name" type="xs:string"/>
  <xs:element name="genre">

    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="category" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>

  </xs:element>
  <xs:element name="band" type="xs:string"/>
  <xs:element name="song_name" type="xs:string"/>
  <xs:element name="video">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="available" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="awards">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="won1" use="optional"/>
          <xs:attribute type="xs:string" name="won2" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="IMVD_rating">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute ref="scale" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="lead_singer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="singer_first_name"/>
        <xs:element ref="singer_middle_name" minOccurs="0"/>
        <xs:element ref="singer_last_name"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="title" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="director">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="director_first_name"/>
        <xs:element ref="director_middle_name" minOccurs="0"/>
        <xs:element ref="director_last_name"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="title" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="producer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="producer_first_name"/>
        <xs:element ref="producer_middle_name" minOccurs="0"/>
        <xs:element ref="producer_last_name"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="title" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="writer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="writer_first_name"/>
        <xs:element ref="writer_middle_name" minOccurs="0"/>
        <xs:element ref="writer_last_name"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="title" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="price" type="xs:int"/>
  <xs:element name="released_date" type="xs:date"/>
  <xs:element name="comment" type="xs:string"/>
  <xs:element name="singer_middle_name" type="xs:string"/>
  <xs:element name="director_middle_name" type="xs:string"/>
  <xs:element name="producer_middle_name" type="xs:string"/>
  <xs:element name="writer_middle_name" type="xs:string"/>

  <xs:attribute name="song_id">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[A][0-9][0-9]"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="scale">
    <xs:simpleType>
      <xs:restriction base="xs:short">
        <xs:pattern value="[0-9]"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:element name="song">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="genre"/>
        <xs:element ref="band"/>
        <xs:element ref="song_name"/>
        <xs:element ref="video" minOccurs="0"/>
        <xs:element ref="awards" minOccurs="0"/>
        <xs:element ref="IMVD_rating" minOccurs="0"/>
        <xs:element ref="lead_singer"/>
        <xs:element ref="director"/>
        <xs:element ref="producer"/>
        <xs:element ref="writer"/>
        <xs:element ref="price"/>
        <xs:element ref="released_date"/>
        <xs:element ref="comment" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute ref="song_id" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="name" type="xs:string"/>
  <xs:element name="address" type="xs:string"/>
  <xs:element name="telephone_number">
      <xs:simpleType>
        <xs:restriction base="xs:int">
          <xs:pattern value="[0][2][1][0-9][0-9][0-9][0-9][0-9]"/>
        </xs:restriction>
      </xs:simpleType>
  </xs:element>

  <xs:element name="email_address" type="xs:string"/>
  <xs:element name="website_address" type="xs:anyURI"/>
  <xs:element name="logo" type="xs:string"/>
  <xs:element name="songs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="song" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="musical_store">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="address"/>
        <xs:element ref="telephone_number"/>
        <xs:element ref="email_address"/>
        <xs:element ref="website_address"/>
        <xs:element ref="logo"/>
        <xs:element ref="songs"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="xsinoNamespaceSchemaLocation"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== NagendraThakur/Music-Store-XML/catalog_19031172.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Developer: Nagendra Thakur Sharma
  Date: 5/2/2021
-->
<!DOCTYPE musical_store SYSTEM "19031172.dtd">
<?xml-stylesheet type="text/css" href="catalog_19031172.css"?>
<musical_store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_19031172.xsd">
   <name>Universial Musical Store</name>
   <address>Biratnagar, Nepal</address>
   <telephone_number>02144157</telephone_number>
   <email_address>UniversialMusicalStore@gmail.com</email_address>
   <website_address>www.UniversialMusicalStore.com</website_address>
   <logo></logo>
   <songs>
      <song song_id="A01">
         <genre category="Rock" />
         <band>Greta Van Fleet</band>
         <song_name>New Day</song_name>
         <video available="yes" />
         <awards won1="grammy" won2="JUNOS" />
         <IMVD_rating scale="8" />
         <lead_singer title="Mr.">
            <singer_first_name>John</singer_first_name>
            <singer_last_name>Kiszka</singer_last_name>
         </lead_singer>
         <director title="Mr.">
            <director_first_name>Jake</director_first_name>
            <director_last_name>Kiszka</director_last_name>
         </director>
         <producer title="Mr.">
            <producer_first_name>Sam</producer_first_name>
            <producer_last_name>Kiszka</producer_last_name>
         </producer>
         <writer title="Mr.">
            <writer_first_name>Daniel</writer_first_name>
            <writer_last_name>Wagner</writer_last_name>
         </writer>
         <price>10000</price>
         <released_date>2016-01-16</released_date>
         <comment>It is a great song.</comment>
      </song>
      <song song_id="A02">
         <genre category="Progressive_Metal" />
         <band>Pink Floyd</band>
         <song_name>Another Brick in the Wall</song_name>
         <awards won1="grammy" won2="JUNOS" />
         <IMVD_rating scale="7" />
         <lead_singer title="Mr.">
            <singer_first_name>Davil</singer_first_name>
            <singer_last_name>Gilmour</singer_last_name>
         </lead_singer>
         <director title="Mr.">
            <director_first_name>Roger</director_first_name>
            <director_last_name>Waters</director_last_name>
         </director>
         <producer title="Mr.">
            <producer_first_name>Richard</producer_first_name>
            <producer_last_name>Wright</producer_last_name>
         </producer>
         <writer title="Mr.">
            <writer_first_name>Syd</writer_first_name>
            <writer_last_name>Barrett</writer_last_name>
         </writer>
         <price>5000</price>
         <released_date>1975-11-30</released_date>
      </song>
      <song song_id="A03">
         <genre category="Alt_Metal" />
         <band>Audioslave</band>
         <song_name>Show Me How to Live</song_name>
         <video available="yes" />
         <awards won1="grammy"/>
         <lead_singer title="Mr.">
            <singer_first_name>Chris</singer_first_name>
            <singer_middle_name>Louise</singer_middle_name>
            <singer_last_name>Cornell</singer_last_name>
         </lead_singer>
         <director title="Mr.">
            <director_first_name>Tom</director_first_name>
            <director_last_name>Morello</director_last_name>
         </director>
         <producer title="Mr.">
            <producer_first_name>Tim</producer_first_name>
            <producer_last_name>Commerford</producer_last_name>
         </producer>
         <writer title="Mr.">
            <writer_first_name>Brad</writer_first_name>
            <writer_last_name>Wilk</writer_last_name>
         </writer>
         <price>9000</price>
         <released_date>2002-06-02</released_date>
         <comment>It is a great song.</comment>
      </song>
      <song song_id="A04">
         <genre category="Progressive_Metal" />
         <band>Porcupine Tree</band>
         <song_name>Arriving Somewhere but Not Here</song_name>
         <video available="yes" />
         <lead_singer title="Mr.">
            <singer_first_name>Steven</singer_first_name>
            <singer_last_name>Wilson</singer_last_name>
         </lead_singer>
         <director title="Mr.">
            <director_first_name>John</director_first_name>
            <director_last_name>Wesley</director_last_name>
         </director>
         <producer title="Mr.">
            <producer_first_name>Gavin</producer_first_name>
            <producer_last_name>Harrison</producer_last_name>
         </producer>
         <writer title="Mr.">
            <writer_first_name>Richard</writer_first_name>
            <writer_last_name>Barbieri</writer_last_name>
         </writer>
         <price>12000</price>
         <released_date>2005-10-11</released_date>
         <comment>It is a great song.</comment>
      </song>
      <song song_id="A05">
         <genre category="Classic_Metal" />
         <band>Led Zeppelin</band>
         <song_name>Stairway to Heaven</song_name>
         <video available="yes" />
         <awards won2="JUNOS" />
         <IMVD_rating scale="5" />
         <lead_singer title="Mr.">
            <singer_first_name>Jimmy</singer_first_name>
            <singer_last_name>Page</singer_last_name>
         </lead_singer>
         <director title="Mr.">
            <director_first_name>Robert</director_first_name>
            <director_last_name>Plant</director_last_name>
         </director>
         <producer title="Mr.">
            <producer_first_name>John</producer_first_name>
            <producer_last_name>Drummer</producer_last_name>
         </producer>
         <writer title="Mr.">
            <writer_first_name>John</writer_first_name>
            <writer_last_name>Bonham</writer_last_name>
         </writer>
         <price>14000</price>
         <released_date>1969-11-08</released_date>
      </song>
      <song song_id="A06">
         <genre category="Pop" />
         <band>Twenty One Pilots</band>
         <song_name>Stressed Out</song_name>
         <video available="yes" />
         <lead_singer title="Mr.">
            <singer_first_name>Tyler</singer_first_name>
            <singer_last_name>Joseph</singer_last_name>
         </lead_singer>
         <director title="Mr.">
            <director_first_name>Josh</director_first_name>
            <director_last_name>Dun</director_last_name>
         </director>
         <producer title="Mr.">
            <producer_first_name>Chris</producer_first_name>
            <producer_last_name>Salih</producer_last_name>
         </producer>
         <writer title="Mr.">
            <writer_first_name>Nick</writer_first_name>
            <writer_last_name>Thomas</writer_last_name>
         </writer>
         <price>3000</price>
         <released_date>2015-04-27</released_date>
         <comment>It is a great song.</comment>
      </song>
      <song song_id="A07">
         <genre category="Noe_Folk" />
         <band>The Lumineers</band>
         <song_name>Angela</song_name>
         <video available="yes" />
         <lead_singer title="Mr.">
            <singer_first_name>Wesley</singer_first_name>
            <singer_last_name>Schultz</singer_last_name>
         </lead_singer>
         <director title="Mr.">
            <director_first_name>Jay</director_first_name>
            <director_middle_name>Van</director_middle_name>
            <director_last_name>Dyke</director_last_name>
         </director>
         <producer title="Mr.">
            <producer_first_name>Neyla</producer_first_name>
            <producer_last_name>Pekarek</producer_last_name>
         </producer>
         <writer title="Mr.">
            <writer_first_name>Jeremiah</writer_first_name>
            <writer_last_name>Fraites</writer_last_name>
         </writer>
         <price>8000</price>
         <released_date>2016-04-01</released_date>
      </song>
      <song song_id="A08">
         <genre category="Noe_Folk" />
         <band>The Lumineers</band>
         <song_name>Stubborn Love</song_name>
         <video available="yes" />
         <awards won1="grammy" won2="JUNOS" />
         <IMVD_rating scale="8" />
         <lead_singer title="Mr.">
            <singer_first_name>Wesley</singer_first_name>
            <singer_last_name>Schultz</singer_last_name>
         </lead_singer>
         <director title="Mr.">
            <director_first_name>Jay</director_first_name>
            <director_middle_name>Van</director_middle_name>
            <director_last_name>Dyke</director_last_name>
         </director>
         <producer title="Mr.">
            <producer_first_name>Neyla</producer_first_name>
            <producer_last_name>Pekarek</producer_last_name>
         </producer>
         <writer title="Mr.">
            <writer_first_name>Jeremiah</writer_first_name>
            <writer_last_name>Fraites</writer_last_name>
         </writer>
         <price>10000</price>
         <released_date>2016-11-16</released_date>
         <comment>It is a great song.</comment>
      </song>
      <song song_id="A09">
         <genre category="Pop" />
         <band>Hozier</band>
         <song_name>Take Me To Church</song_name>
         <video available="yes" />
         <awards won1="grammy" won2="JUNOS" />
         <IMVD_rating scale="7" />
         <lead_singer title="Mr.">
            <singer_first_name>Hozier</singer_first_name>
            <singer_last_name>Bray</singer_last_name>
         </lead_singer>
         <director title="Mr.">
            <director_first_name>James</director_first_name>
            <director_last_name>Mary</director_last_name>
         </director>
         <producer title="Mr.">
